TOP_BAR_TITLE_SETTINGS_MENU:
  en: "Settings menu"
  ja: "設定メニュー"
  fr: ""
  nl: ""
  zh_TW: ""
  pl_pl: ""
  de: ""
  pt_br: ""
  uk_UA: ""
  ru_RU: ""
TOP_BAR_TITLE_PROJECT_SETTINGS_MENU:
  en: "Project settings menu"
  ja: "プロジェクトの設定メニュー"
  fr: ""
  nl: ""
  zh_TW: ""
  pl_pl: ""
  de: ""
  pt_br: ""
  uk_UA: ""
  ru_RU: ""
STATUS_UNSAVED_CHANGES:
  en: "Unsaved changes!"
  ja: ""
  fr: ""
  nl: ""
  zh_TW: ""
  pl_pl: ""
  de: ""
  pt_br: ""
  uk_UA: ""
  ru_RU: ""
STATUS_CHANGES_SAVED:
  en: "Changes saved!"
  ja: ""
  fr: ""
  nl: ""
  zh_TW: ""
  pl_pl: ""
  de: ""
  pt_br: ""
  uk_UA: ""
  ru_RU: ""
BUTTON_CANCEL:
  en: "Cancel"
  ja: "キャンセル"
  fr: ""
  nl: ""
  zh_TW: ""
  pl_pl: ""
  de: ""
  pt_br: ""
  uk_UA: ""
  ru_RU: ""
BUTTON_SAVE:
  en: "Save"
  ja: "保存"
  fr: ""
  nl: ""
  zh_TW: ""
  pl_pl: ""
  de: ""
  pt_br: ""
  uk_UA: ""
  ru_RU: ""
TOOLTIP_BUTTON_CANCEL:
  en: "Cancel without saving settings"
  ja: ""
  fr: ""
  nl: ""
  zh_TW: ""
  pl_pl: ""
  de: ""
  pt_br: ""
  uk_UA: ""
  ru_RU: ""
TOOLTIP_BUTTON_SAVE:
  en: "Save unsaved changes"
  ja: ""
  fr: ""
  nl: ""
  zh_TW: ""
  pl_pl: ""
  de: ""
  pt_br: ""
  uk_UA: ""
  ru_RU: ""
TOOLTIP_BUTTON_EXIT:
  en: "Exit GoZen settings menu"
  ja: ""
  fr: ""
  nl: ""
  zh_TW: ""
  pl_pl: ""
  de: ""
  pt_br: ""
  uk_UA: ""
  ru_RU: ""
SECTION_GENERAL:
  en: "General settings"
  ja: ""
  fr: ""
  nl: ""
  zh_TW: ""
  pl_pl: ""
  de: ""
  pt_br: ""
  uk_UA: ""
  ru_RU: ""
SETTING_ZEN_MODE:
  en: "Zen mode"
  ja: ""
  fr: ""
  nl: ""
  zh_TW: ""
  pl_pl: ""
  de: ""
  pt_br: ""
  uk_UA: ""
  ru_RU: ""
TOOLTIP_SETTING_ZEN_MODE:
  en: "Zen mode hides certain elements and creates a more minimized looking layout."
  ja: ""
  fr: ""
  nl: ""
  zh_TW: ""
  pl_pl: ""
  de: ""
  pt_br: ""
  uk_UA: ""
  ru_RU: ""
SETTING_LANGUAGE:
  en: "Language"
  ja: "言語"
  fr: ""
  nl: ""
  zh_TW: ""
  pl_pl: ""
  de: ""
  pt_br: ""
  uk_UA: ""
  ru_RU: ""
TOOLTIP_SETTING_LANGUAGE:
  en: "Change the language of the UI."
  ja: ""
  fr: ""
  nl: ""
  zh_TW: ""
  pl_pl: ""
  de: ""
  pt_br: ""
  uk_UA: ""
  ru_RU: ""
CLOSE_DIALOG_TEXT:
  en: "You have unsaved changes, do you want to save these before closing?"
  ja: ""
  fr: ""
  nl: ""
  zh_TW: ""
  pl_pl: ""
  de: ""
  pt_br: ""
  uk_UA: ""
  ru_RU: ""
CLOSE_DIALOG_BUTTON_CANCEL:
  en: "Don't save"
  ja: ""
  fr: ""
  nl: ""
  zh_TW: ""
  pl_pl: ""
  de: ""
  pt_br: ""
  uk_UA: ""
  ru_RU: ""
CLOSE_DIALOG_BUTTON_OK:
  en: "Save"
  ja: ""
  fr: ""
  nl: ""
  zh_TW: ""
  pl_pl: ""
  de: ""
  pt_br: ""
  uk_UA: ""
  ru_RU: ""
EMPTY:
  en: ""
  ja: ""
  fr: ""
  nl: ""
  zh_TW: ""
  pl_pl: ""
  de: ""
  pt_br: ""
  uk_UA: ""
  ru_RU: ""
